### ISSUE TITLE
missing GitHub Releases

### ISSUE THREAD

**Issue by clach04** [Villadelfia/DMGTRIS#12]
https://github.com/Villadelfia/dmgtris/releases is empty. I think, there maybe binaries in https://github.com/Villadelfia/dmgtris/tree/master/bin ?

Not had chance to check it out yet but saw it featured in a video https://youtu.be/D5gOTwHBR5s?si=UMwBc7CAxKwlEL_A and it looks awesome 👍 Thanks for working on this!

**Comment by Villadelfia** [comment]
Oh yeah, I never made an actual release. Just did one.
