### ISSUE TITLE
I'm siked!

### ISSUE THREAD

**Issue by Gertris** [Villadelfia/DMGTRIS#13]
Last night I accidentally stumbled on this while surfing the web!
I've been jonesing for some tgm like action like this on my pocket.  I think Apotris is really nice, but I was hoping for something more concentrated towards TGM and this I think hits the sweetspot. 
I have it on the switch, but it lacks the excitement I get from playing on a CRT or gameboy screen that I grew up with back in the glory days.  

I've been playing TGM1 a lot lately using the playstation romhack, and have very recently started being able to hit GM! woo!
Getting GM of course does not at all end the obsession.  Now I want to see how far I can get in BIG mode and/or 20G...

Being able to grab a gameboy, or analog pocket and practice anywhere really scratches a certain itch.  

Thank you for making this a reality!

**Comment by Villadelfia** [comment]
I'm glad you're enjoying it! It makes me happy to see people enjoy the game.
