### ISSUE TITLE
Shouldn't the score for hard drops take into account the number of lines dropped?

### ISSUE THREAD

**Issue by Superegz** [Villadelfia/DMGTRIS#5]
I see that while soft drops are counted, harddrops are given a universal 10 point bonus. This means that there are times when you can get less points from hard dropping rather than soft dropping. 

Wouldn't it make more sense for hard dropping to be better rewarded such as by giving 2 points for each line hard dropped?

**Comment by Villadelfia** [comment]
This was actually the plan! But... I forgot...

Thanks for reminding me.

**Comment by Villadelfia** [comment]
Implemented.

**Comment by Superegz** [comment]
Awesome! Thanks. Love the game by the way!

**Comment by Villadelfia** [comment]
Glad you enjoy it :D
