### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Villadelfia** [Villadelfia/DMGTRIS#6]
Add dark mode in game play

**Comment by Villadelfia** [comment]
Implemented.

**Comment by CreepercraftYT** [comment]
change the grade, score and level numbers to white

**Comment by CreepercraftYT** [comment]
because rn they're almost unreadable on dark mode xd (big mode)

and also, the "grade" frame doesn't appear on big mode either

**Comment by Villadelfia** [comment]
Fixed. Please create new issues for bugs instead of commenting on old ones.

**Comment by CreepercraftYT** [comment]
ok
